const NAVIGATION_PREFIX = 'IN_';
export const ROOT = `${NAVIGATION_PREFIX}Root`;
const APP_SCREEN = `${NAVIGATION_PREFIX}APP_SCREEN`;
const SIDE_MENU = `${NAVIGATION_PREFIX}SIDE_MENU`;
const LOADING_SCREEN = `${NAVIGATION_PREFIX}LOADING_SCREEN`;
const LOGIN_SCREEN = `${NAVIGATION_PREFIX}LOGIN_SCREEN`;
const ALERT_POPUP = `${NAVIGATION_PREFIX}ALERT_POPUP`;
const HOME_SCREEN = `${NAVIGATION_PREFIX}HOME_SCREEN`;
const NEW_PAGE_SCREEN = `${NAVIGATION_PREFIX}NEW_PAGE_SCREEN`;
const NEW_POST_SCREEN = `${NAVIGATION_PREFIX}NEW_POST_SCREEN`;
const CONTACT_SCREEN = `${NAVIGATION_PREFIX}CONTACT_SCREEN`;
const OTHER_SCREEN = `${NAVIGATION_PREFIX}OTHER_SCREEN`;
const MY_PROFILE_SCREEN = `${NAVIGATION_PREFIX}MY_PROFILE_SCREEN`;
const POST_SAVED_SCREEN = `${NAVIGATION_PREFIX}POST_SAVED_SCREEN`;
const PAYMENT_SCREEN = `${NAVIGATION_PREFIX}PAYMENT_SCREEN`;
const MY_POST_SCREEN = `${NAVIGATION_PREFIX}MY_POST_SCREEN`;
const CHANGE_PASSWORD_SCREEN = `${NAVIGATION_PREFIX}CHANGE_PASSWORD_SCREEN`;
const SIGN_UP_SCREEN = `${NAVIGATION_PREFIX}SIGN_UP_SCREEN`;
const FORGOT_PASSWORD_SCREEN = `${NAVIGATION_PREFIX}FORGOT_PASSWORD_SCREEN`;
const VERIFY_CODE_SCREEN = `${NAVIGATION_PREFIX}VERIFY_CODE_SCREEN`;
export {
  SIDE_MENU,
  LOADING_SCREEN,
  HOME_SCREEN,
  LOGIN_SCREEN,
  APP_SCREEN,
  ALERT_POPUP,
  NEW_PAGE_SCREEN,
  NEW_POST_SCREEN,
  CONTACT_SCREEN,
  OTHER_SCREEN,
  MY_PROFILE_SCREEN,
  POST_SAVED_SCREEN,
  PAYMENT_SCREEN,
  CHANGE_PASSWORD_SCREEN,
  MY_POST_SCREEN,
  SIGN_UP_SCREEN,
  FORGOT_PASSWORD_SCREEN,
  VERIFY_CODE_SCREEN,
};
