const NAVIGATION_PREFIX = 'IN_';
export const ROOT = `${NAVIGATION_PREFIX}Root`;
const APP_SCREEN = `${NAVIGATION_PREFIX}APP_SCREEN`;
const SIDE_MENU = `${NAVIGATION_PREFIX}SIDE_MENU`;
const LOADING_SCREEN = `${NAVIGATION_PREFIX}LOADING_SCREEN`;
const HOME_SCREEN = `${NAVIGATION_PREFIX}HOME_SCREEN`;
const LOGIN_SCREEN = `${NAVIGATION_PREFIX}LOGIN_SCREEN`;
const CART_SCREEN = `${NAVIGATION_PREFIX}CART_SCREEN`;
const DRAW_SCREEN = `${NAVIGATION_PREFIX}DRAW_SCREEN`;
const SETTING_SCREEN = `${NAVIGATION_PREFIX}SETTING_SCREEN`;
const COMPONENT_SCREEN = `${NAVIGATION_PREFIX}COMPONENT_SCREEN`;
const IMAGE_PICKER_SCREEN = `${NAVIGATION_PREFIX}IMAGE_PICKER_SCREEN`;
const OVERLAY_SCREEN = `${NAVIGATION_PREFIX}OVERLAY_SCREEN`;
const PICKER_SELECT_SCREEN = `${NAVIGATION_PREFIX}PICKER_SELECT_SCREEN`;
const SEARCH_BAR_SCREEN = `${NAVIGATION_PREFIX}SEARCH_BAR_SCREEN`;
const TOAST_SCREEN = `${NAVIGATION_PREFIX}TOAST_SCREEN`;
const ALERT_POPUP = `${NAVIGATION_PREFIX}ALERT_POPUP`;

export {
  SIDE_MENU,
  LOADING_SCREEN,
  HOME_SCREEN,
  LOGIN_SCREEN,
  CART_SCREEN,
  DRAW_SCREEN,
  APP_SCREEN,
  SETTING_SCREEN,
  COMPONENT_SCREEN,
  IMAGE_PICKER_SCREEN,
  OVERLAY_SCREEN,
  PICKER_SELECT_SCREEN,
  SEARCH_BAR_SCREEN,
  TOAST_SCREEN,
  ALERT_POPUP,
};
