/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:697d1118-1b70-4c7f-b969-8ce4698a878b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rs1bzlOgQ",
    "aws_user_pools_web_client_id": "3bifnhmpaeg443c552nb30dgkq",
    "oauth": {
        "domain": "leaveapplicationapp017bed50-017bed50-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "leave://",
        "redirectSignOut": "leave://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_user_files_s3_bucket": "bucketleave143636-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
